import { db, persist } from "./db.js";
import { getKeywords } from "./keywords.js";

// Real Roblox avatar photos for the player list.
//
// Pipeline:
//   1) SCRAPE  -> users.roblox.com/v1/users/search returns real usernames.
//   2) RESOLVE -> thumbnails.roblox.com/v1/users/avatar-headshot returns the
//                 actual avatar photo URL for each userId.
//   3) CACHE   -> results are persisted so repeat calls are instant and don't
//                 hammer the Roblox API.
//
// If a username/avatar doesn't exist or the API fails, it's simply skipped;
// the frontend shows a monogram fallback, so there is never a broken image.

const SEARCH_URL = "https://users.roblox.com/v1/users/search";
const THUMB_URL = "https://thumbnails.roblox.com/v1/users/avatar-headshot";
const AVATAR_SIZE = "150x150";
const SCRAPE_INTERVAL = 20 * 60 * 1000; // refresh scraped pool at most every 20m
const POOL_CAP = 4000;

// A LARGE, varied pool of search keywords (hundreds to thousands), generated by
// combining prefixes + themes + suffixes in keywords.js. We scrape a rotating
// subset each refresh so the avatar pool never looks repetitive.
let freshSeed = 1;
function getKeywordBatch(batchSize) {
  freshSeed++;
  return getKeywords(batchSize, `batch-${Date.now()}-${freshSeed}`);
}

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

async function scrapePool(keywords) {
  const found = [];
  const selected = shuffle(keywords).slice(0, 6);
  await Promise.all(
    selected.map(async (kw) => {
      try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 2500);
        const r = await fetch(`${SEARCH_URL}?keyword=${encodeURIComponent(kw)}&limit=30`, {
          headers: { "user-agent": "fullmoon-finder/1.0" },
          signal: controller.signal,
        });
        clearTimeout(timeout);
        if (!r.ok) return;
        const j = await r.json();
        (j.data || []).forEach((u) => {
          if (u.id && u.name) found.push({ id: u.id, name: u.name, displayName: u.displayName || u.name });
        });
      } catch {
        /* ignore keyword failures */
      }
    })
  );
  return found;
}

async function fetchThumbnails(ids) {
  if (ids.length === 0) return {};
  const chunkSize = 100;
  const map = {};
  for (let i = 0; i < ids.length; i += chunkSize) {
    const chunk = ids.slice(i, i + chunkSize);
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 3000);
      const url = `${THUMB_URL}?userIds=${chunk.join(",")}&size=${AVATAR_SIZE}&format=Png&isCircular=true`;
      const r = await fetch(url, { headers: { "user-agent": "fullmoon-finder/1.0" }, signal: controller.signal });
      clearTimeout(timeout);
      if (!r.ok) continue;
      const j = await r.json();
      (j.data || []).forEach((item) => {
        if (item.state === "Completed" && item.imageUrl) {
          map[item.targetId] = item.imageUrl;
        }
      });
    } catch {
      /* ignore chunk failures */
    }
  }
  return map;
}

const poolUsers = () => db.roblox_users || [];
const avatarCache = () => db.roblox_avatars || {};

// Ensure we have enough scraped candidates available.
async function ensurePool(minSuccess) {
  const need = Math.max(poolUsers().length, minSuccess * 3);
  if (poolUsers().length >= minSuccess && Date.now() - (db.roblox_last_scrape || 0) < SCRAPE_INTERVAL) {
    return;
  }
  try {
    const batch = getKeywordBatch(3000);
    const found = await scrapePool(batch);
    const known = new Set(poolUsers().map((u) => u.id));
    const merged = [...poolUsers(), ...found.filter((u) => !known.has(u.id))];
    db.roblox_users = merged.slice(0, POOL_CAP);
    db.roblox_last_scrape = Date.now();
    persist();
  } catch {
    /* keep whatever we have */
  }
}

// De-duplicated: returns a fresh username pool entry that has a cached avatar.
function availableWithAvatar() {
  const cache = avatarCache();
  return poolUsers().filter((u) => cache[u.id]);
}

export async function getAvatars(count) {
  const target = Math.min(Math.max(1, count), 120);

  // Fast path: if enough cached avatars are already available, respond instantly
  const ready = availableWithAvatar();
  if (ready.length >= target) {
    const chosen = shuffle(ready).slice(0, target);
    const cache = avatarCache();
    return chosen.map((u) => ({ id: u.id, name: u.name, displayName: u.displayName || u.name, avatarUrl: cache[u.id] }));
  }

  // Otherwise top up the pool safely
  try {
    await ensurePool(target * 3);

    let attempts = 0;
    while (availableWithAvatar().length < target && attempts < 4) {
      const cache = avatarCache();
      const missing = poolUsers().filter((u) => !cache[u.id]).slice(0, 100);
      if (missing.length === 0) break;
      const map = await fetchThumbnails(missing.map((u) => u.id));
      let added = 0;
      for (const u of missing) {
        if (map[u.id]) {
          db.roblox_avatars[u.id] = map[u.id];
          added++;
        }
      }
      if (added === 0) break;
      persist();
      attempts++;
    }
  } catch {
    /* fallback to whatever is available */
  }

  const cache = avatarCache();
  const candidates = poolUsers().filter((u) => cache[u.id]);
  const chosen = shuffle(candidates.length ? candidates : poolUsers()).slice(0, target);
  return chosen.map((u) => ({ id: u.id, name: u.name, displayName: u.displayName || u.name, avatarUrl: cache[u.id] || null }));
}

// Count of avatars we can serve instantly from cache (for introspection/debug).
export function cachedAvatarCount() {
  return availableWithAvatar().length;
}
