// Moon model: 8 phases with a deterministic "nights until next full moon".
// A server's phase is generated by the engine; the nights count derives from
// it so the icon/label/status are always mutually consistent.

export const PHASES = [
  { key: "full",           label: "Full Moon",      icon: "🌕" },
  { key: "waning_gibbous", label: "Waning Gibbous", icon: "🌖" },
  { key: "third_quarter",  label: "Third Quarter",  icon: "🌗" },
  { key: "waning_crescent",label: "Waning Crescent",icon: "🌘" },
  { key: "new",            label: "New Moon",       icon: "🌑" },
  { key: "waxing_crescent",label: "Waxing Crescent",icon: "🌒" },
  { key: "first_quarter",  label: "First Quarter",  icon: "🌓" },
  { key: "waxing_gibbous", label: "Waxing Gibbous", icon: "🌔" },
];

// Forward distance (in phases) to the next Full Moon.
export function nightsToFull(phaseKey) {
  const idx = PHASES.findIndex((p) => p.key === phaseKey);
  if (idx < 0) return 0;
  return (8 - idx) % 8; // full -> 0, waxing_gibbous -> 1, first_quarter -> 2, ...
}

export function phaseInfo(key) {
  return PHASES.find((p) => p.key === key) || PHASES[4];
}

// Servers further than this many nights away are considered "far from the
// full moon" and are replaced by the engine.
export const FAR_NIGHTS = 3;
export const isNearFull = (phaseKey) => nightsToFull(phaseKey) < FAR_NIGHTS;
export const isFullMoon = (phaseKey) => phaseKey === "full";

export function formatMoonStatus(phaseKey) {
  if (isFullMoon(phaseKey)) return "FULL MOON";
  const n = nightsToFull(phaseKey);
  return `${n} more night${n === 1 ? "" : "s"}.`;
}
